version: "3.9"
services:
  node1:
    build: .
    environment:
      NODE_ID: "node1:8000"
      HOST: "0.0.0.0"
      PORT: "8000"
      PEERS: "node2:8000,node3:8000"
      DATA_DIR: "/data"
    volumes:
      - node1_data:/data
    ports:
      - "8001:8000"
  node2:
    build: .
    environment:
      NODE_ID: "node2:8000"
      HOST: "0.0.0.0"
      PORT: "8000"
      PEERS: "node1:8000,node3:8000"
      DATA_DIR: "/data"
    volumes:
      - node2_data:/data
    ports:
      - "8002:8000"
  node3:
    build: .
    environment:
      NODE_ID: "node3:8000"
      HOST: "0.0.0.0"
      PORT: "8000"
      PEERS: "node1:8000,node2:8000"
      DATA_DIR: "/data"
    volumes:
      - node3_data:/data
    ports:
      - "8003:8000"

volumes:
  node1_data:
  node2_data:
  node3_data:
